### ISSUE TITLE
missing a call to unregisterReceiver()

### ISSUE THREAD

**Issue by ghost** [pwittchen/ReactiveNetwork#172]
```
E/ActivityThread: Activity  has leaked IntentReceiver com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy$2@d5e8688 that was originally registered here. 
Are you missing a call to unregisterReceiver()?
android.app.IntentReceiverLeaked: Activity com.xdja.xypolice.ui.DotToDotActivty has leaked IntentReceiver com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy$2@d5e8688 that was originally registered here. Are you missing a call to unregisterReceiver()?
  at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:999)
  at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:795)
  at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1329)
  at android.app.ContextImpl.registerReceiver(ContextImpl.java:1309)
  at android.app.ContextImpl.registerReceiver(ContextImpl.java:1303)
  at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
  at com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy.registerIdleReceiver(MarshmallowNetworkObservingStrategy.java:81)
  at com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy.observeNetworkConnectivity(MarshmallowNetworkObservingStrategy.java:53)
  at com.github.pwittchen.reactivenetwork.library.rx2.ReactiveNetwork.observeNetworkConnectivity(ReactiveNetwork.java:95)
  at com.github.pwittchen.reactivenetwork.library.rx2.ReactiveNetwork.observeNetworkConnectivity(ReactiveNetwork.java:76)
```

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting that issue.

Have you disposed subscription in onPause() method in your activity? When
you missed it, such problem may occur.

08.05.2017 11:44 AM "CentForever" <notifications@github.com> napisał(a):

**Comment by pwittchen** [comment]
Please let me know if that suggestion helped you. If not, please provide steps to reproduce this problem and your code snippet, so I could verify this issue.

**Comment by Bhavdip** [comment]
I think he forgot to unregister or should clear the subscriber from listening to the update in activity.

**Comment by pwittchen** [comment]
@Bhavdip probably you're right. That's what I wrote in my first reply to this issue.

**Comment by pwittchen** [comment]
There was no response for a longer time, so I assume it's incorrect library usage. For further issues, please re-open this one or create a new one.
