### ISSUE TITLE
Error: Could not establish connection with WalledGardenStrategy

### ISSUE THREAD

**Issue by sevar83** [pwittchen/ReactiveNetwork#228]
Hi, I am flooded with this exception the entire time:

```
E: Could not establish connection with WalledGardenStrategy
                          java.net.SocketTimeoutException: timeout
                              at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
                              at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
                              at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                              at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                              at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
                              at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
                              at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
                              at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy.isConnected(WalledGardenInternetObservingStrategy.java:100)
                              at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy$1.apply(WalledGardenInternetObservingStrategy.java:63)
                              at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy$1.apply(WalledGardenInternetObservingStrategy.java:61)
                              at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
                              at com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:57)
                              at io.reactivex.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:83)
                              at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:416)
                              at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:371)
                              at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                              at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                              at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                              at java.lang.Thread.run(Thread.java:764)
                           Caused by: java.net.SocketException: Socket closed
                              at java.net.SocketInputStream.read(SocketInputStream.java:203)
                              at java.net.SocketInputStream.read(SocketInputStream.java:139)
                              at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
                              at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306) 
                              at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300) 
                              at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196) 
                              at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186) 
                              at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) 
                              at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737) 
                              at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609) 
                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471) 
                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407) 
                              at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538) 
                              at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy.isConnected(WalledGardenInternetObservingStrategy.java:100) 
                              at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy$1.apply(WalledGardenInternetObservingStrategy.java:63) 
                              at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy$1.apply(WalledGardenInternetObservingStrategy.java:61) 
                              at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59) 
                              at com.tspoon.traceur.ObservableOnAssembly$OnAssemblyObserver.onNext(ObservableOnAssembly.java:57) 
                              at io.reactivex.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:83) 
                              at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:416) 
                              at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:371) 
                              at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61) 
                              at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52) 
                              at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                              at java.lang.Thread.run(Thread.java:764) 
```

My code is very simple:

```
val viewStates: Observable<ConnectivityState> = ReactiveNetwork.observeInternetConnectivity()
                .subscribeOn(Schedulers.io())
                .map(::ConnectivityState)
                .observeOn(AndroidSchedulers.mainThread())

class ConnectivityState(
        val connected: Boolean = true
)
```

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting the issue.

Message says:

```
Could not establish connection with WalledGardenStrategy
                          java.net.SocketTimeoutException: timeout
```

so your device couldn't establish socket connection and connection timeout occurred. Are you sure this issue is not related to your device or network you have been connected to? Maybe you were behind a proxy, connected via VPN or something like that?

I don't think this code in the very basic version is not working because it was already tested some time ago and everything was fine.

**Comment by sevar83** [comment]
That's on API26 on the emulator. It happens from time to time not always.
It's strange because I have a connection and all the data in the app loads
up. Even the connectivity observable is emitting properly. And google.com
opens up in Chrome. My connection is laggy, maybe the socket connection
timeout runs out. I'm going to ignore this for awhile.

**Comment by pwittchen** [comment]
This issue seems to be related to unreliable Internet connection and connections timeout - not the library itself, so it can be closed.

**Comment by RagnarR** [comment]
@sevar83 use this in your `<application>` tag: `android:usesCleartextTraffic="true"`

**Comment by dmbee** [comment]
I am having the same issue on API 25, intermittent 
```
019-02-22 14:50:57.332 8035-8319/com.halterix.halterix E/ReactiveNetwork: Could not establish connection with WalledGardenStrategy
    java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
        at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy.isConnected(WalledGardenInternetObservingStrategy.java:103)
        at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy$1.apply(WalledGardenInternetObservingStrategy.java:64)
        at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy$1.apply(WalledGardenInternetObservingStrategy.java:62)
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57)
        at io.reactivex.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:82)
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:532)
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:479)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:151)
        at java.net.SocketInputStream.read(SocketInputStream.java:120)
        at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306) 
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300) 
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196) 
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191) 
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80) 
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906) 
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521) 
        at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy.isConnected(WalledGardenInternetObservingStrategy.java:103) 
        at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy$1.apply(WalledGardenInternetObservingStrategy.java:64) 
        at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy$1.apply(WalledGardenInternetObservingStrategy.java:62) 
        at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:57) 
        at io.reactivex.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:82) 
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:532) 
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:479) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
```

**Comment by jido2015** [comment]
Why is this happening even if i don't have strong network? Is there a way we can catch or just stop this error from crashing app?

**Comment by pwittchen** [comment]
@jido2015 You can handle it with `onError` method in subscribtion like any RxJava observable.

**Comment by jido2015** [comment]
Thank you! I mailed you already
