### ISSUE TITLE
Error receiving broadcast Intent: PreLollipopNetworkObservingStrategy

### ISSUE THREAD

**Issue by VisheshVadhera** [pwittchen/ReactiveNetwork#257]
**Stacktrace:**

```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in com.github.pwittchen.reactivenetwork.library.network.observing.strategy.PreLollipopNetworkObservingStrategy$1$1@220df588
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:778)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5257)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)

Caused by java.lang.IllegalStateException: more items arrived than were requested
       at rx.internal.producers.ProducerArbiter.produced(ProducerArbiter.java:98)
       at rx.internal.operators.OnSubscribeSwitchIfEmpty$ParentSubscriber.onNext(OnSubscribeSwitchIfEmpty.java:122)
       at com.github.pwittchen.reactivenetwork.library.network.observing.strategy.PreLollipopNetworkObservingStrategy$1$1.onReceive(PreLollipopNetworkObservingStrategy.java:51)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5257)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
```

**OS:** 4.4.2

**Manufacturer:** Asus

**Phone model:** ZenFone 5 (A501CG)

**Library version:** 0.12.0, RxJava 1

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting that issue. I suppose it's the same problem as here: https://github.com/pwittchen/ReactiveWiFi/issues/28. I'll bump version of RxJava1.x and it should fix that problem.

Regards,
Piotr

**Comment by VisheshVadhera** [comment]
Hey Piotr,

Thanks for the quick reply. Should I open a PR for this?

**Comment by pwittchen** [comment]
You can, if you'd like to.

**Comment by VisheshVadhera** [comment]
Perfect, I'll open it.

**Comment by pwittchen** [comment]
PR merged. Update should be available in the next release. You can monitor release progress in #258.
In case of further problems, we can re-open this issue or create a new one.
