### ISSUE TITLE
WalledGardenInternetObservingStrategy error

### ISSUE THREAD

**Issue by AtaerCaner** [pwittchen/ReactiveNetwork#267]
Hello I get two different error in _WalledGardenInternetObservingStrategy_ that caused to crash. 

**First:**

```
Fatal Exception: io.reactivex.exceptions.OnErrorNotImplementedException: length=8192; index=8192
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
       at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```
**Second:** 

```
Caused by java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192
       at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:818)
       at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:793)
       at com.android.okhttp.okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:57)
       at com.android.okhttp.internal.http.HttpConnection.writeRequest(HttpConnection.java:172)
       at com.android.okhttp.internal.http.HttpTransport.writeRequestHeaders(HttpTransport.java:76)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:766)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
       at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy.isConnected(WalledGardenInternetObservingStrategy.java:100)
       at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy$1.apply(WalledGardenInternetObservingStrategy.java:63)
       at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.WalledGardenInternetObservingStrategy$1.apply(WalledGardenInternetObservingStrategy.java:61)
       at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
       at io.reactivex.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:83)
       at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:416)
       at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:371)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:776)
```
**-----------**

Do you know the reason and did you solve these in last version? Thank you.

**Version:**  reactivenetwork-rx2:0.12.1

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue.

**First problem**:

You haven't specified error handler during observing the Internet and something went wrong (e.g. connection timeout, no Internet, no WiFi connection, wrong address, etc.). You should handle it as follows:

```java
ReactiveNetwork
   .observeInternetConnectivity()
   .subscribeOn(Schedulers.io())
   .observeOn(AndroidSchedulers.mainThread())
   .subscribe(
       response  -> /* handle response here */,
       throwable -> /* handle error here */)
   );
```

You can do it with any kind of RxJava Observable type. I should update documentation a little bit.

**Second problem**:

StackTrace starts at:

```
 at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:818)
 ...
```

so I suppose it's related to the OkHttp library. I'm not using it in this library, so I suppose Android guys have put it into Android OS Core or maybe you're using it in your app or one of your dependencies is using it. Nevertheless, it's runtime error related to observing Internet (similar to the first problem) and **you should be able to handle it in the same way as the first problem**.

Regards,
Piotr

**Comment by AtaerCaner** [comment]
I understand Piotr. Thank you for the quick response

**Comment by pwittchen** [comment]
Ok, when it's clarified, we can close this issue.
