### ISSUE TITLE
RN crashes app (SocketObservingStrategy doesn't check for errors)

### ISSUE THREAD

**Issue by intari** [pwittchen/ReactiveNetwork#290]
I got following crash log in my app (I use SocketInternetObservingStrategy right now)

```
Fatal Exception: io.reactivex.exceptions.OnErrorNotImplementedException: Host is unresolved: clients3.google.com/generate_204
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
       at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
       at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
       at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
       at android.os.Handler.handleCallback(Handler.java:800)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5560)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
       at dalvik.system.NativeStart.main(NativeStart.java)

Caused by java.net.UnknownHostException: Host is unresolved: clients3.google.com/generate_204
       at java.net.Socket.connect(Socket.java:837)
       at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.SocketInternetObservingStrategy.isConnected(SocketInternetObservingStrategy.java:127)
       at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.SocketInternetObservingStrategy.isConnected(SocketInternetObservingStrategy.java:110)
       at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.SocketInternetObservingStrategy$1.apply(SocketInternetObservingStrategy.java:60)
       at com.github.pwittchen.reactivenetwork.library.rx2.internet.observing.strategy.SocketInternetObservingStrategy$1.apply(SocketInternetObservingStrategy.java:58)
       at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
       at io.reactivex.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:83)
       at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:533)
       at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:480)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)

```

**Comment by pwittchen** [comment]
First of all, you haven't handled an error.

It can be done as follows:

```java
observable
 .subscribe(
    connectivity -> /* handle connectivity */,
    error -> /*handle an error */
  );
```

as in any RxJava observable.

The library doesn't handle these errors. It just throws them. You can handle them in any way you want.

Second, please make sure that your network has Internet access and you're able to access host `clients3.google.com/generate_204`.

Moreover, your network could be temporarily slower and an Internet connection could be down.

**Comment by intari** [comment]
Sorry.
I didn't thought I have to handle errors here (I thought that - DNS(or other) connectivity error = no connectivity and should be reported as 'no connectivity').
I will now handle it myself as such.

**Comment by pwittchen** [comment]
In several cases, you will get an information about no connectivity (e.g. `IOException` or when host address will be resolved, but you won't be able to establish the connection). In the special cases like `java.net.UnknownHostException`, errors will be thrown and you can notify the user about lack of connectivity anyway. In the most cases, it's good to handle RxJava errors in any way.

**Comment by pwittchen** [comment]
This issue was clarified, so we can close it now.
