### ISSUE TITLE
Unregister receiver crash for Pre-Lollipop devices

### ISSUE THREAD

**Issue by Kisty** [pwittchen/ReactiveNetwork#87]
Got a crash on an Asus Transformer (API 16) when rotating the device. I unsubscribe in `onPause` and subscribe in `onResume` but I think there's a problem unregistering the receiver if it's not attached.

I have a subscription from it to a `BehaviourSubject` and multiple subscriptions from the `BehaviourSubject` to other subscribers.

```
09-29 11:04:31.350 1174-1174/uk.co.imagitech.learn2.hp E/ActivityThread: Activity uk.co.imagitech.learn2.hp.MainActivity has leaked IntentReceiver com.github.pwittchen.reactivenetwork.library.network.observing.strategy.PreLollipopNetworkObservingStrategy$1$1@416c8ad0 that was originally registered here. Are you missing a call to unregisterReceiver()?
     android.app.IntentReceiverLeaked: Activity uk.co.imagitech.learn2.hp.MainActivity has leaked IntentReceiver com.github.pwittchen.reactivenetwork.library.network.observing.strategy.PreLollipopNetworkObservingStrategy$1$1@416c8ad0 that was originally registered here. Are you missing a call to unregisterReceiver()?
         at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:792)
         at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:593)
         at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1120)
         at android.app.ContextImpl.registerReceiver(ContextImpl.java:1107)
         at android.app.ContextImpl.registerReceiver(ContextImpl.java:1101)
         at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:365)
         at com.github.pwittchen.reactivenetwork.library.network.observing.strategy.PreLollipopNetworkObservingStrategy$1.call(PreLollipopNetworkObservingStrategy.java:50)
         at com.github.pwittchen.reactivenetwork.library.network.observing.strategy.PreLollipopNetworkObservingStrategy$1.call(PreLollipopNetworkObservingStrategy.java:42)
         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
         at rx.Observable.unsafeSubscribe(Observable.java:10150)
         at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
         at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
         at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
         at java.util.concurrent.FutureTask.run(FutureTask.java:137)
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
         at java.lang.Thread.run(Thread.java:856)
09-29 11:04:31.360 1174-1174/uk.co.imagitech.learn2.hp E/AndroidRuntime: FATAL EXCEPTION: main
     java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
         at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
         at android.os.Handler.handleCallback(Handler.java:615)
         at android.os.Handler.dispatchMessage(Handler.java:92)
         at android.os.Looper.loop(Looper.java:137)
         at android.app.ActivityThread.main(ActivityThread.java:4745)
         at java.lang.reflect.Method.invokeNative(Native Method)
         at java.lang.reflect.Method.invoke(Method.java:511)
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
         at dalvik.system.NativeStart.main(Native Method)
      Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.github.pwittchen.reactivenetwork.library.network.observing.strategy.PreLollipopNetworkObservingStrategy$1$1@416c8ad0
         at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:654)
         at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1143)
         at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:378)
         at com.github.pwittchen.reactivenetwork.library.network.observing.strategy.PreLollipopNetworkObservingStrategy$1$2.call(PreLollipopNetworkObservingStrategy.java:54)
         at com.github.pwittchen.reactivenetwork.library.network.observing.strategy.PreLollipopNetworkObservingStrategy$2$1.call(PreLollipopNetworkObservingStrategy.java:71)
         at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
         at android.os.Handler.handleCallback(Handler.java:615) 
         at android.os.Handler.dispatchMessage(Handler.java:92) 
         at android.os.Looper.loop(Looper.java:137) 
         at android.app.ActivityThread.main(ActivityThread.java:4745) 
         at java.lang.reflect.Method.invokeNative(Native Method) 
         at java.lang.reflect.Method.invoke(Method.java:511) 
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
         at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue.

StackTrace says that `Receiver not registered`. Actually, the receiver should be registered when observable is subscribed and unregistered when observable is unsubscribed in UI thread. It may be a concurrency issue. How do you unsubscribe your Observable? I think the safest method is to do it in the following way:

```java
if (subscription != null && !subscription.isUnsubscribed()) {
  subscription.unsubscribe();
}
```

Remember, that subscription can be null and we need to check it. Moreover, we need to check if subscription wasn't already unsubscribed.

**Comment by Kisty** [comment]
Hey thanks for getting back to me.

I must admit I am new to RxJava, but I hae followed that pattern where you subscribe in `onResume` and unsubscribe in `onPause`. I do unsubscribe safely in the way you have outlined but I still got a crash. As I have multiple subscriptions, I add them to a `CompositeSubscription`.

I think there's just a small window where this crash can happen as the unsubscribe call is executed on the UI thread. I've seen other developers with similar issues. See http://stackoverflow.com/a/3568906/818821

```
    @Override
    protected void onResume() {
        super.onResume();

        subscriptions = new CompositeSubscription();

        Subscriber<Connectivity> connectivitySubscriber = new Subscriber<Connectivity>() {
            @Override
            public void onCompleted() {

            }

            @Override
            public void onError(Throwable e) {
                Timber.e(e, "Problem with connectivity subscriber");
            }

            @Override
            public void onNext(Connectivity connectivity) {
                NetworkInfo.State state = connectivity.getState();
                if (state == NetworkInfo.State.CONNECTED) {
                    if (connectivity.getType() == ConnectivityManager.TYPE_MOBILE) {
                        if (!UserPreferences.getDataAllowOnceMeteredConnection(MainActivity.this)
                                && !UserPreferences.getDataAlwaysAllowMeteredConnection(MainActivity.this)) {
                            MeteredDialogFragment.newInstance(R.string.dialog_metered_network_stream_videos).show(getSupportFragmentManager(), MeteredDialogFragment.TAG);
                        }
                    }
                    connected = true;
                } else if (state == NetworkInfo.State.DISCONNECTED) {
                    //Show dialog if not shown
                    if (!offlineDialogShown) {
                        OfflineDialogFragment.newInstance(R.string.dialog_message_menu_offline).show(getSupportFragmentManager(), OfflineDialogFragment.TAG);
                        offlineDialogShown = true;
                    }
                    connected = false;
                }
                if (!isFinishing()) {
                    //Refresh menu items
                    refreshContentPager();
                }
                Timber.d("Connectivity changed: %s", connectivity.toString());
                BeeLog.d("MainActivity", String.format("Connectivity changed: %s", connectivity.toString()));
            }
        };
        Observable<Connectivity> observable = createConnectivityObservable();
        //Make it a behaviour subject so that it stores the last value and emits that value to any subscribers
        //Assume it's connected to wifi else if we give disconnected, it will fire offline dialog
        connectivityBehaviourSubject = BehaviorSubject.create(Connectivity.create(NetworkInfo.State.CONNECTED, ConnectivityManager.TYPE_WIFI, "WIFI"));
        Subscription subscription1 = observable.subscribe(connectivityBehaviourSubject);
        Subscription subscription2 = connectivityBehaviourSubject.subscribe(connectivitySubscriber);

        //TODO check if both are needed
        subscriptions.add(subscription1);
        subscriptions.add(subscription2);
    }

    @RxLogObservable
    private Observable<Connectivity> createConnectivityObservable() {
        return ReactiveNetwork.observeNetworkConnectivity(this)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .filter(Connectivity.hasState(NetworkInfo.State.CONNECTED, NetworkInfo.State.DISCONNECTED))
                .distinctUntilChanged();
    }

    @Override
    protected void onPause() {
        super.onPause();

        subscriptions.unsubscribe();
    }
```

**Comment by Polyterative** [comment]
I still have this happening when calling from a service. android 9.

EDIT: happens in activity, not service

**Comment by pwittchen** [comment]
Do you get the same error?

**Comment by Polyterative** [comment]
Yup
```log
D: NetworkCallback was already unregistered
E: could not unregister receiver
    java.lang.IllegalArgumentException: Receiver not registered: com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy$4@7ddb4f9
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1429)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1543)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:664)
        at com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy.tryToUnregisterReceiver(MarshmallowNetworkObservingStrategy.java:148)
        at com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy$3.run(MarshmallowNetworkObservingStrategy.java:85)
        at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.cancel(FlowableDoOnLifecycle.java:115)
        at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.cancel(FlowableFlatMap.java:353)
        at io.reactivex.internal.subscriptions.SubscriptionArbiter.drainLoop(SubscriptionArbiter.java:221)
        at io.reactivex.internal.subscriptions.SubscriptionArbiter.drain(SubscriptionArbiter.java:190)
        at io.reactivex.internal.subscriptions.SubscriptionArbiter.cancel(SubscriptionArbiter.java:182)
        at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
        at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.dispose(ObservableFromPublisher.java:70)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.dispose(ObservableObserveOn.java:146)
        at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.dispose(ObservableDoOnEach.java:79)
        at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.dispose(ObservableObserveOn.java:146)
        at io.reactivex.internal.operators.observable.ObservableSkip$SkipObserver.dispose(ObservableSkip.java:72)
        at io.reactivex.internal.observers.BasicFuseableObserver.dispose(BasicFuseableObserver.java:152)
        at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
        at io.reactivex.internal.operators.observable.ObservablePublishAlt$PublishConnection.dispose(ObservablePublishAlt.java:161)
        at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
        at io.reactivex.internal.operators.observable.ObservableRefCount.timeout(ObservableRefCount.java:136)
        at io.reactivex.internal.operators.observable.ObservableRefCount.cancel(ObservableRefCount.java:103)
        at io.reactivex.internal.operators.observable.ObservableRefCount$RefCountObserver.dispose(ObservableRefCount.java:232)
        at com.uber.autodispose.AutoDisposableHelper.dispose(AutoDisposableHelper.java:44)
        at com.uber.autodispose.AutoDisposingObserverImpl$1.onComplete(AutoDisposingObserverImpl.java:61)
        at io.reactivex.internal.operators.observable.ObservableIgnoreElementsCompletable$IgnoreObservable.onComplete(ObservableIgnoreElementsCompletable.java:66)
        at io.reactivex.internal.operators.observable.ObservableTakeUntilPredicate$TakeUntilPredicateObserver.onNext(ObservableTakeUntilPredicate.java:79)
        at io.reactivex.internal.operators.observable.ObservableSkip$SkipObserver.onNext(ObservableSkip.java:56)
        at com.uber.autodispose.android.lifecycle.LifecycleEventsObservable$ArchLifecycleObserver.onStateChange(LifecycleEventsObservable.java:122)
        at com.uber.autodispose.android.lifecycle.LifecycleEventsObservable_ArchLifecycleObserver_LifecycleAdapter.callMethods(LifecycleEventsObservable_ArchLifecycleObserver_LifecycleAdapter.java:22)
E:     at androidx.lifecycle.SingleGeneratedAdapterObserver.onStateChanged(SingleGeneratedAdapterObserver.java:30)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:316)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:334)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:123)
        at androidx.lifecycle.ReportFragment.onDestroy(ReportFragment.java:108)
        at android.app.Fragment.performDestroy(Fragment.java:2794)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1456)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
        at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3032)
        at android.app.FragmentController.dispatchDestroy(FragmentController.java:250)
        at android.app.Activity.performDestroy(Activity.java:8047)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1334)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4926)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4970)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
I've registered my stream like this

```kotlin
open class MyActivityStarter : AppCompatActivity() {
    [...]
    protected lateinit var networkStatusStream: Observable<NetworkInfo.State>

    override fun onCreate(savedInstanceState: Bundle?) {
       
		[...]

        networkStatusStream = ReactiveNetwork
            .observeNetworkConnectivity(applicationContext)
            .observeOn(Schedulers.io())
            .map { it.state() }
            .doOnNext { Logger.v("Network state changed: $it") }
            .share()

	}
}
```

In every Activity I have I extend `MyActivityStarter` and listen for `networkStatusStream` events

**Comment by Polyterative** [comment]
Using v3.0.6 of the lib

**Comment by pwittchen** [comment]
I'm not sure if it's not related with the `share()` method. In previous cases people didn't use it. Do you dispose these observables? If they're not disposed, it may cause errors like this.

**Comment by AhmedMourad0** [comment]
v3.0.8 and still getting the same error, even if I wrap the observable in a LiveData it still produces the same error.

I'm not using `share` either:

```
ReactiveNetwork.observeNetworkConnectivity(appCtx)
                .subscribeOn(Schedulers.io())
                .observeOn(Schedulers.io())
                .switchMapSingle { ReactiveNetwork.checkInternetConnectivity() }
                .toFlowable(BackpressureStrategy.LATEST)
                .retry()
                .observeOn(AndroidSchedulers.mainThread())
                .toLiveData()
```

**Comment by pwittchen** [comment]
@AhmedMourad0 Have you tried to test this without `retry()`? I think using `retry()` in this case is not the best idea, because `observeNetworkConnectivity(context)` method wraps `BroadcastReceiver` which is controlled by the Android system - not the app. Due to this fact, we cannot _force_ retry this call. It will be invoked by the system and we don't know when. This method just spawns the `BroadcastReceiver`, which is listening to the system events. To wrap up, I think, using `retry()` may be problematic here.

You can do this trick with `ReactiveNetwork.checkInternetConnectivity()` method only because it pings remote server instead of listening to the system events. It depends, what your app needs.

**edit**: 
I looked at the code once again and I see that there's `switchMapSingle`, which should invoke the `retry()` only on the latest `Flowable` stream (`ReactiveNetwork.checkInternetConnectivity()` in this case), so this code should work. I'll try to have a look at this.

**Comment by AhmedMourad0** [comment]
Thank you for the quick reply!

I've been trying with it a little, I removed the `retry` and the LiveData entirely, still getting the same error.

It seems to happen when I press the home button and come back to the app, even though I do subscribe in `onStart` and dispose in `onStop`.

The testing device is a Huawei Y7 Prime 2018 and the Android version is Oreo 8.0.0

This's the entire stacktrace:
```
E/ReactiveNetwork: could not unregister receiver
    java.lang.IllegalArgumentException: Receiver not registered: com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy$4@cb520f5
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1292)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1629)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:639)
        at com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy.tryToUnregisterReceiver(MarshmallowNetworkObservingStrategy.java:148)
        at com.github.pwittchen.reactivenetwork.library.rx2.network.observing.strategy.MarshmallowNetworkObservingStrategy$3.run(MarshmallowNetworkObservingStrategy.java:85)
        at io.reactivex.internal.operators.flowable.FlowableDoOnLifecycle$SubscriptionLambdaSubscriber.cancel(FlowableDoOnLifecycle.java:115)
        at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.cancel(FlowableFlatMap.java:358)
        at io.reactivex.internal.subscriptions.SubscriptionArbiter.drainLoop(SubscriptionArbiter.java:221)
        at io.reactivex.internal.subscriptions.SubscriptionArbiter.drain(SubscriptionArbiter.java:190)
        at io.reactivex.internal.subscriptions.SubscriptionArbiter.cancel(SubscriptionArbiter.java:182)
        at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
        at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.dispose(ObservableFromPublisher.java:70)
        at io.reactivex.internal.disposables.DisposableHelper.dispose(DisposableHelper.java:124)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.dispose(ObservableSubscribeOn.java:73)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.dispose(ObservableObserveOn.java:146)
        at io.reactivex.internal.operators.mixed.ObservableSwitchMapSingle$SwitchMapSingleMainObserver.dispose(ObservableSwitchMapSingle.java:165)
        at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.cancel(FlowableFromObservable.java:64)
        at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.cancel(FlowableOnBackpressureLatest.java:96)
        at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
        at io.reactivex.internal.subscribers.SinglePostCompleteSubscriber.cancel(SinglePostCompleteSubscriber.java:124)
        at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.cancel(FlowableObserveOn.java:154)
        at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:181)
        at io.reactivex.internal.subscribers.LambdaSubscriber.cancel(LambdaSubscriber.java:119)
        at io.reactivex.internal.subscribers.LambdaSubscriber.dispose(LambdaSubscriber.java:104)
        at dev.ahmedmourad.sherlock.android.view.activity.MainActivity.onStop(MainActivity.kt:493)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1386)
        at android.app.Activity.performStop(Activity.java:7587)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4802)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4858)
        at android.app.ActivityThread.-wrap25(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2028)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by pwittchen** [comment]
I think, you should subscribe in `onResume()` and dispose Disposable in `onPause()` instead of `onStart()` and `onStop()`.

**Comment by AhmedMourad0** [comment]
That does indeed seem to be the problem, although, unfortunately, not `LiveData` friendly, moving to `onResume` and `onPause` solves this issue.

Thank you!

**Comment by pwittchen** [comment]
Great! So we can close this issue now.
